language: python
dist: xenial
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_install:
  - python setup.py install
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests/test_centrality.py
  - python tests/test_graphvals.py
  - python tests/test_nulls.py
  - python tests/test_sets.py
  - python tests/test_stats.py